import { MembershipTier, Restaurant, User } from "./types";

export const MOCK_USER: User = {
  id: "u1",
  name: "Nguyễn Văn A",
  email: "nguyenvana@example.com",
  avatar: "https://picsum.photos/200/200",
  tier: MembershipTier.GOLD,
  points: 1250,
  totalSpent: 15800000,
  history: [
    {
      id: "h1",
      restaurantName: "Phở Anh Hai",
      date: "2024-05-10",
      total: 150000,
      items: ["Phở Bò Đặc Biệt", "Quẩy"],
    },
    {
      id: "h2",
      restaurantName: "Gà Chiên Mắm Tỏi",
      date: "2024-05-05",
      total: 850000,
      items: ["Combo Sashimi", "Sake"],
    },
    {
      id: "h3",
      restaurantName: "Lẩu Thái Hải Sản",
      date: "2024-04-20",
      total: 200000,
      items: ["Double Cheese Burger", "Coke"],
    },
    {
      id: "h4",
      restaurantName: "Phở Anh Hai",
      date: "2024-04-15",
      total: 120000,
      items: ["Phở Gà", "Trà đá"],
    },
  ],
};

export const RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    name: "Phở Anh Hai",
    address: "123 Nguyễn Trãi, Hà Nội",
    rating: 4.8,
    image: "/images/pho.jpg",
    category: "Món Việt",
    priceRange: "$$",
    description:
      "Hương vị phở truyền thống gia truyền 30 năm. Nước dùng ninh xương ống 24h.",
    lat: 21.0,
    lng: 105.8,
    menu: [
      {
        id: "m1",
        name: "Phở Bò Tái",
        price: 55000,
        image: "/images/ca_phe_sua_da.jpg",
        description: "Bò tái mềm ngọt",
      },
      {
        id: "m2",
        name: "Phở Gà Ta",
        price: 50000,
        image: "/images/bia.jpg",
        description: "Gà ta da giòn",
      },
    ],
    reviews: [
      {
        id: "rv1",
        userId: "u2",
        userName: "Tran B",
        rating: 5,
        comment: "Nước dùng rất ngọt, thịt mềm.",
        date: "2024-05-01",
        restaurantId: "r1",
      },
    ],
  },
  {
    id: "r2",
    name: "Sushi Master",
    address: "45 Lê Lợi, TP. HCM",
    rating: 4.5,
    image: "",
    category: "Nhật Bản",
    priceRange: "$$$",
    description: "Sashimi tươi sống nhập khẩu trực tiếp từ Nhật Bản mỗi ngày.",
    lat: 10.7,
    lng: 106.6,
    menu: [
      {
        id: "m3",
        name: "Sashimi Cá Hồi",
        price: 150000,
        image: "https://picsum.photos/202",
        description: "5 miếng tươi ngon",
      },
      {
        id: "m4",
        name: "Cơm Lươn Nhật",
        price: 250000,
        image: "https://picsum.photos/203",
        description: "Lươn nướng sốt Kabayaki",
      },
    ],
    reviews: [],
  },
  {
    id: "r3",
    name: "Burger Town",
    address: "88 Trần Hưng Đạo, Đà Nẵng",
    rating: 4.2,
    image: "",
    category: "Âu Mỹ",
    priceRange: "$$",
    description: "Burger bò Mỹ nướng than hoa thơm lừng.",
    lat: 16.0,
    lng: 108.2,
    menu: [],
    reviews: [],
  },
  {
    id: "r4",
    name: "Vegetarian Soul",
    address: "10 Ngô Quyền, Huế",
    rating: 4.9,
    image: "",
    category: "Chay",
    priceRange: "$",
    description: "Món chay thanh tịnh, tốt cho sức khỏe.",
    lat: 16.4,
    lng: 107.5,
    menu: [],
    reviews: [],
  },
];
