import { MembershipTier, Restaurant, User } from "./types";

export const MOCK_USER: User = {
  id: "u1",
  name: "Trần Lê Tuấn",
  email: "nguyenvana@example.com",
  avatar: "images/banTuan.jpg",
  tier: MembershipTier.GOLD,
  points: 1250,
  totalSpent: 15800000,
  history: [
    {
      id: "h1",
      restaurantName: "Phở Anh Hai",
      date: "2024-05-10",
      total: 150000,
      items: ["Phở Bò Đặc Biệt", "Quẩy"],
    },
    {
      id: "h2",
      restaurantName: "Gà Chiên Mắm Tỏi",
      date: "2024-05-05",
      total: 850000,
      items: ["Combo Sashimi", "Sake"],
    },
    {
      id: "h3",
      restaurantName: "Lẩu Thái Hải Sản",
      date: "2024-04-20",
      total: 200000,
      items: ["Double Cheese Burger", "Coke"],
    },
    {
      id: "h4",
      restaurantName: "Phở Anh Hai",
      date: "2024-04-15",
      total: 120000,
      items: ["Phở Gà", "Trà đá"],
    },
  ],
};

export const RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    name: "Phở Anh Hai",
    address: "123 Nguyễn Trãi, Hà Nội",
    rating: 4.8,
    image: "/images/pho.jpg",
    category: "Món Việt",
    priceRange: "$$",
    description:
      "Hương vị phở truyền thống gia truyền 30 năm. Nước dùng ninh xương ống 24h.",
    lat: 21.0,
    lng: 105.8,
    menu: [
      {
        id: "m1",
        name: "Phở Bò Tái",
        price: 55000,
        image: "/images/pho-tai-bo-vien.jpg",
        description: "Bò tái mềm ngọt",
      },
      {
        id: "m2",
        name: "Phở Gà Ta",
        price: 50000,
        image: "/images/pho_ga_ta.jpg",
        description: "Gà ta da giòn",
      },
      {
      id: "m4",
      name: "Bánh Quẩy",
      price: 10000,
      image: "/images/banh_quay.jpg",
      description: "Quẩy giòn nóng, thơm nhẹ, chấm cùng nước phở hoặc ăn kèm giúp tăng độ béo và hương vị cho tô phở.",
      },
    ],
    reviews: [
      {
        id: "rv1",
        userId: "u2",
        userName: "Tran B",
        rating: 5,
        comment: "Nước dùng rất ngọt, thịt mềm.",
        date: "2024-05-01",
        restaurantId: "r1",
      },
    ],
  },
  {
    id: "r2",
    name: "Sushi",
    address: "45 Lê Lợi, TP. HCM",
    rating: 4.5,
    image: "/images/Sushi.jpg",
    category: "Nhật Bản",
    priceRange: "$$$",
    description: "Sashimi tươi sống nhập khẩu trực tiếp từ Nhật Bản mỗi ngày.",
    lat: 10.7,
    lng: 106.6,
    menu: [
      {
        id: "m5",
        name: "Sashimi Cá Hồi",
        price: 150000,
        image: "/images/sashimi-ca-hoi.jpg",
        description: "5 miếng tươi ngon",
      },
      {
        id: "m6",
        name: "Cơm Lươn Nhật",
        price: 75000,
        image: "/images/Com_Luon.jpg",
        description: "Lươn nướng sốt Kabayaki",
      },
      {
        id: "m7",
        name: "Udon Nhật",
        price: 80000,
        image: "/images/Udon.jpg",
        description: "Mì sợi to, dai mềm đặc trưng của Nhật Bản, dùng với nước dùng thanh nhẹ, đậm vị umami, thường ăn kèm tempura hoặc thịt.",
      },
      {
        id: "m8",
        name: "Bánh xèo Nhật",
        price: 750000,
        image: "/images/banh-xeo-nhat-ban.jpg",
        description: "Bánh áp chảo mềm xốp, bắp cải và trứng, phủ sốt Nhật đặc trưng.",
      },
    ],
    reviews: [],
  },
  {
    id: "r3",
    name: "Burger",
    address: "88 Trần Hưng Đạo, Đà Nẵng",
    rating: 4.2,
    image: "/images/burger.jpg",
    category: "Âu Mỹ",
    priceRange: "$$",
    description: "Burger bò Mỹ nướng than hoa thơm lừng.",
    lat: 16.0,
    lng: 108.2,
    menu: [
    {
        id: "m9",
        name: "Burger size M",
        price: 60000,
        image: "/images/burgerM.jpg",
        description: "Phần tiêu chuẩn, vừa đủ cho một bữa ăn nhẹ.",
      },
    {
        id: "m10",
        name: "Burger size L",
        price: 85000,
        image: "/images/burgerX.jpg",
        description: "Khẩu phần lớn hơn, no hơn, phù hợp người ăn khỏe.",
      },
    {
        id: "m9",
        name: "Burger size XL",
        price: 120000,
        image: "/images/burgerXL.jpg",
        description: "Size đại, nhiều nhân và bánh, dành cho người ăn rất khỏe.",
      }, 
    ],
    reviews: [],
  },
  {
    id: "r4",
    name: "Vegetarian",
    address: "10 Ngô Quyền, Huế",
    rating: 4.9,
    image: "/images/Chay.jpg",
    category: "Chay",
    priceRange: "$",
    description: "Món chay thanh tịnh, tốt cho sức khỏe.",
    lat: 16.4,
    lng: 107.5,
    menu: [
  {
    id: "m20",
    name: "Phở Chay",
    price: 45000,
    image: "/images/pho_chay.jpg",
    description: "Phở chay thanh đạm, nước dùng nấu từ rau củ và nấm.",
  },
  {
    id: "m21",
    name: "Bún Riêu Chay",
    price: 50000,
    image: "/images/bun_rieu_chay.jpg",
    description: "Bún riêu chay với đậu hũ, cà chua và nước dùng đậm vị.",
  },
  {
    id: "m22",
    name: "Cơm Chiên Rau Củ",
    price: 40000,
    image: "/images/com_chien_chay.jpg",
    description: "Cơm chiên chay thập cẩm, rau củ tươi và gia vị vừa ăn.",
  },
  {
    id: "m23",
    name: "Mì Xào Chay",
    price: 45000,
    image: "/images/mi_xao_chay.jpg",
    description: "Mì xào chay với nấm, rau xanh và nước sốt đậm đà.",
  },
  {
    id: "m24",
    name: "Đậu Hũ Sốt Nấm",
    price: 55000,
    image: "/images/dau_hu_sot_nam.jpg",
    description: "Đậu hũ chiên mềm, sốt nấm thơm béo, ăn kèm cơm trắng.",
  },
],
    reviews: [],
  },
  {
    id: "r4",
    name: "Water Seven",
    address: "2627 Hùng Vương, Ba Ngòi, Cam Ranh, Khánh Hòa",
    rating: 4.2,
    image: "/images/NuocGiaiKhat.jpg",
    category: "Âu Mỹ",
    priceRange: "$$",
    description: "Burger bò Mỹ nướng than hoa thơm lừng.",
    lat: 16.0,
    lng: 108.2,
    menu: [
  {
    id: "d1",
    name: "Trà Đá",
    price: 5000,
    image: "/images/Tra_da.jpg",
    description: "Trà đá mát lạnh, giải khát nhẹ khi dùng bữa.",
  },
  {
    id: "d2",
    name: "Trà Chanh",
    price: 15000,
    image: "/images/tra_chanh.jpg",
    description: "Trà chanh chua nhẹ, thanh mát và dễ uống.",
  },
  {
    id: "d3",
    name: "Trà Đào",
    price: 25000,
    image: "/images/tra_dao.jpg",
    description: "Trà đào thơm dịu, vị ngọt thanh, uống lạnh rất ngon.",
  },
  {
    id: "d4",
    name: "Nước Cam",
    price: 30000,
    image: "/images/nuoc_cam.jpg",
    description: "Nước cam tươi vắt, giàu vitamin C.",
  },
  {
    id: "d5",
    name: "Nước Ép Táo",
    price: 30000,
    image: "/images/nuoc-ep-tao.jpg",
    description: "Nước ép táo tươi, vị ngọt tự nhiên.",
  },
  {
    id: "d6",
    name: "Coca-Cola",
    price: 20000,
    image: "/images/coca.jpg",
    description: "Nước ngọt có gas mát lạnh, quen thuộc.",
  },
  {
    id: "d7",
    name: "Pepsi",
    price: 20000,
    image: "/images/pepsi.jpg",
    description: "Nước ngọt có gas, vị cola đậm đà.",
  },
  {
    id: "d8",
    name: "Nước Suối",
    price: 10000,
    image: "/images/nuoc_suoi.jpg",
    description: "Nước suối tinh khiết, dùng hằng ngày.",
  },
],
    reviews: [],
  },
];
