from enum import Enum

# API / paging defaults
API_VERSION = "v1"
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100


class UserRole(str, Enum):
	SYS_ADMIN = "SYS_ADMIN"
	OWNER = "OWNER"
	STAFF = "STAFF"
	CUSTOMER = "CUSTOMER"


class OrderStatus(str, Enum):
	PENDING = "PENDING"
	CONFIRMED = "CONFIRMED"
	COOKING = "COOKING"
	SERVED = "SERVED"
	COMPLETED = "COMPLETED"
	CANCELLED = "CANCELLED"


class TableStatus(str, Enum):
	AVAILABLE = "AVAILABLE"
	OCCUPIED = "OCCUPIED"
	RESERVED = "RESERVED"


class PaymentStatus(str, Enum):
	PENDING = "PENDING"
	PAID = "PAID"
	FAILED = "FAILED"
	REFUNDED = "REFUNDED"


class PaymentMethod(str, Enum):
	CASH = "CASH"
	CARD = "CARD"
	VIETQR = "VIETQR"
	BANK_TRANSFER = "BANK_TRANSFER"
	DIGITAL_WALLET = "DIGITAL_WALLET"


class PromotionType(str, Enum):
	PERCENTAGE = "PERCENTAGE"
	FIXED_AMOUNT = "FIXED_AMOUNT"
	BUY_ONE_GET_ONE = "BUY_ONE_GET_ONE"
